# Generated by Django 2.2.2 on 2019-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=120)),
                ('med_disaese', models.CharField(max_length=120)),
                ('med_brand', models.CharField(default=None, max_length=120, null=True)),
                ('med_dose', models.CharField(default=None, max_length=120, null=True)),
            ],
        ),
    ]
