# Generated by Django 2.2.2 on 2019-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=120)),
                ('doc_address', models.CharField(max_length=120)),
                ('doc_mobile', models.IntegerField(max_length=10)),
                ('doc_speciality', models.CharField(max_length=120)),
                ('doc_experience', models.CharField(max_length=120)),
                ('doc_degree', models.CharField(max_length=120)),
            ],
        ),
    ]
