# Generated by Django 2.2.2 on 2019-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_mobile',
            field=models.IntegerField(),
        ),
    ]
