# Generated by Django 2.2.2 on 2019-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190728_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_location',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
