# Generated by Django 2.2.2 on 2019-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_hospital_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='h_rating',
            field=models.CharField(max_length=120),
        ),
    ]
