# Generated by Django 2.2.2 on 2019-08-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190730_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
    ]
