# Generated by Django 2.2.2 on 2019-08-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_doctor_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_syrup',
            field=models.BooleanField(default=False),
        ),
    ]
