# Generated by Django 2.2.2 on 2019-08-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('project', '0009_medicine_is_syrup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_doctor', models.BooleanField(default=False)),
                ('tag', models.CharField(default=None, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
