# Generated by Django 2.2.2 on 2019-08-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
