# Generated by Django 2.2.2 on 2019-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('query', models.CharField(max_length=200)),
                ('doc_name', models.CharField(default=None, max_length=200, null=True)),
                ('tag', models.CharField(max_length=120)),
                ('answer', models.CharField(default=None, max_length=250, null=True)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
    ]
