# Generated by Django 2.2.2 on 2019-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('feed', models.CharField(max_length=150)),
            ],
        ),
    ]
