# Generated by Django 2.2.2 on 2019-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_consultdoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultdoctor',
            name='speciality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
